# Generated by Django 3.2.8 on 2024-01-11 01:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.FileField(blank=True, null=True, upload_to='static/actas')),
            ],
            options={
                'verbose_name': 'Acta',
                'verbose_name_plural': ' Actas',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, unique=True, verbose_name='Area')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, unique=True, verbose_name='Cargos')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, unique=True, verbose_name='Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Condicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, unique=True, verbose_name='Condicion')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, unique=True, verbose_name='Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, unique=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True, verbose_name='Nombre')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, unique=True, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono')),
                ('nombre_contacto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contacto')),
                ('correo', models.CharField(blank=True, max_length=50, null=True, verbose_name='correo')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': ' Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Tipos_Activos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, unique=True, verbose_name='Tipos Activos')),
            ],
            options={
                'verbose_name': 'Tipo_Activo',
                'verbose_name_plural': ' Tipos_Activos',
            },
        ),
        migrations.CreateModel(
            name='Tipos_Discos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, unique=True, verbose_name='Tipos discos')),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, unique=True, verbose_name='Tipos Licencia')),
            ],
            options={
                'verbose_name': 'Tipo_Licencia',
                'verbose_name_plural': ' Tipos_Licencias',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, unique=True, verbose_name='Ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True, verbose_name='Nombre')),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cedula')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Activos.area')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Activos.cargo')),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Activos.ciudad')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Activos.departamento')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': ' Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True, verbose_name='Nombre')),
                ('version', models.CharField(max_length=30, null=True, verbose_name='Version')),
                ('key', models.CharField(max_length=20, null=True, unique=True, verbose_name='Key')),
                ('fecha_compra', models.DateField(blank=True, null=True, verbose_name='Fecha Compra')),
                ('numero_factura', models.CharField(max_length=30, null=True, verbose_name='Numero Factura')),
                ('precio_compra', models.CharField(max_length=10, null=True, verbose_name='Precio Compra')),
                ('fecha_vigencia', models.DateField(blank=True, null=True, verbose_name='Fecha Vigencia')),
                ('estado', models.BooleanField(blank=True, default=True, verbose_name='Estado')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Activos.proveedor', verbose_name='Proveedor')),
                ('tipos_licencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Activos.tipos_licencia')),
            ],
            options={
                'verbose_name': 'Licencia',
                'verbose_name_plural': ' Licencias',
            },
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tic', models.CharField(max_length=30, null=True, unique=True, verbose_name='TIC')),
                ('evento', models.TextField(blank=True, null=True, verbose_name='Evento')),
                ('modelo', models.CharField(blank=True, max_length=55, null=True, verbose_name='Modelo')),
                ('garantia', models.DateField(blank=True, null=True, verbose_name='Garantia')),
                ('serial', models.CharField(blank=True, max_length=55, null=True, verbose_name='Serial')),
                ('ram', models.CharField(blank=True, max_length=55, null=True, verbose_name='Ram')),
                ('board', models.CharField(blank=True, max_length=55, null=True, verbose_name='Board')),
                ('procesador', models.CharField(blank=True, max_length=55, null=True, verbose_name='Procesador')),
                ('nombre_equipo', models.CharField(blank=True, max_length=59, null=True, verbose_name='Nombre Equipo')),
                ('sistema_operativo', models.CharField(blank=True, max_length=55, null=True, verbose_name='SistemaOperativo')),
                ('ip', models.CharField(blank=True, max_length=55, null=True, verbose_name='Ip')),
                ('pulgadas', models.CharField(blank=True, max_length=55, null=True, verbose_name='Pulgadas')),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Compra')),
                ('fecha_compra', models.DateField(blank=True, null=True, verbose_name='Fecha Compra')),
                ('numero_factura', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero Factura')),
                ('acta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activo_acta', to='Activos.acta')),
                ('condicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Activos.condicion', verbose_name='condicion')),
                ('discos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Activos.tipos_discos')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Activos.estado')),
                ('licencia', models.ManyToManyField(blank=True, related_name='activos_licencia', to='Activos.Licencia')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Activos.marca')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Activos.proveedor')),
                ('tipos_activos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Activos.tipos_activos')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Activos.ubicacion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_usuario', to='Activos.usuario')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': ' Activos',
            },
        ),
        migrations.AddField(
            model_name='acta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acta_usuario', to='Activos.usuario'),
        ),
    ]
