# Generated by Django 3.2.8 on 2024-01-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='sistema_operativo',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Sistema Operativo'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='tic',
            field=models.CharField(max_length=30, null=True, unique=None, verbose_name='TIC'),
        ),
    ]
