# Generated by Django 3.2.8 on 2024-01-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activos', '0003_alter_activo_tic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='tic',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='TIC'),
        ),
    ]
