# Generated by Django 3.2.8 on 2024-01-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activos', '0004_alter_activo_tic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencia',
            name='key',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='version',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Version'),
        ),
    ]
