# Generated by Django 3.2.8 on 2024-01-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activos', '0005_auto_20240111_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencia',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Numero Factura'),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='precio_compra',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Precio Compra'),
        ),
    ]
