# Generated by Django 3.2.8 on 2024-01-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activos', '0007_auto_20240111_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='licencia',
            field=models.ManyToManyField(blank=True, related_name='activos_licencia', to='Activos.Licencia'),
        ),
    ]
