# Generated by Django 3.2.8 on 2024-01-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activos', '0009_remove_proveedor_nit'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='nit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nit'),
        ),
    ]
