# Generated by Django 3.2.8 on 2024-01-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activos', '0011_auto_20240113_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncabezadoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='encabezados/')),
            ],
        ),
    ]
