# Generated by Django 3.2.8 on 2024-01-13 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activos', '0012_encabezadomodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EncabezadoModel',
            new_name='Encabezado',
        ),
    ]
