# Generated by Django 3.2.8 on 2024-01-14 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activos', '0013_rename_encabezadomodel_encabezado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
