# Generated by Django 3.2.8 on 2024-01-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activos', '0014_delete_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='discos',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='discos'),
        ),
        migrations.DeleteModel(
            name='Tipos_Discos',
        ),
    ]
