# Generated by Django 5.0.1 on 2024-02-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activos', '0016_alter_licencia_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencia',
            name='key',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Key'),
        ),
    ]
