# Generated by Django 5.0 on 2024-03-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activos', '0018_alter_licencia_nombre_alter_licencia_precio_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='garantia',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento Garantia'),
        ),
    ]
